# Numpy, vectores y matrices

1. Introducción a numpy 
2. Operaciones matemáticas con numpy (TODO)
3. Ejercicios de algebra lineal (TODO)

# 1. Introducción a numpy
---

Exploraremos el uso de numpy para diversas operaciones con vectores, matrices y tensores.

## Instalación de dependencias

El primer paso es configurar nuestro ambiente. Para eso tenemos que instalar dependencias que no son nativas de python (En este caso [numpy](https://numpy.org/doc/stable/user/quickstart.html)). Para hacer esto en google colab, ejecuta la siguiente linea de código:


In [1]:
!pip install numpy
!pip install matplotlib

   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.9 MB 435.7 kB/s eta 0:00:35
   ---------------------------------------- 0.1/14.9 MB 1.2 MB/s eta 0:00:13
   - -------------------------------------- 0.7/14.9 MB 4.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/14.9 MB 7.9 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/14.9 MB 9.7 MB/s eta 0:00:02
   --------- ------------------------------ 3.4/14.9 MB 10.9 MB/s eta 0:00:02
   ----------- ---------------------------- 4.2/14.9 MB 11.6 MB/s eta 0:00:01
   ------------- -------------------------- 5.0/14.9 MB 11.8 MB/s eta 0:00:01
   --------------- ------------------------ 5.6/14.9 MB 12.0 MB/s eta 0:00:01
   ----------------- ---------------------- 6.4/14.9 MB 12.5 MB/s eta 0:00:01
   -------------------- ------------------- 7.5/14.9 MB 12.9 MB/s eta 0:00:01
   --

## Importar dependencias
Mientras que lo anterior nos permite configurar nuestro ambiente de programación, ahora procederemos a crear nuestro código ejecutable. 

Como en todo lenguaje lo primero que hacemos es importar toda dependencia de la cual haremos uso. En este caso utilizaremos la librería de numpy para manejo de operaciones y matplotlib para visualización de datos.

In [2]:
import numpy as np

     ---------------------------------------- 0.0/162.3 kB ? eta -:--:--
     -- ------------------------------------- 10.2/162.3 kB ? eta -:--:--
     ---------------------- ---------------- 92.2/162.3 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 162.3/162.3 kB 1.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.5 MB 10.9 MB/s eta 0:00:01
   ----- ---------------------------------- 1.0/7.5 MB 10.5 MB/s eta 0:00:01
   -------- ------------------------------- 1.6/7.5 MB 12.4 MB/s eta 0:00:01
   ----------- ---------------------------- 2.2/7.5 MB 12.7 MB/s eta 0:00:01
   --------------- ------------------------ 2.8/7.5 MB 12.9 MB/s eta 0:00:01
   ------------------ --------------------- 3.4/7.5 MB 12.9 MB/s eta 0:00:01
   ---------------------- ----------------- 4.2/7.5 MB 13.4 MB/s eta 0:00:01
   -------------------------- ------------- 5.0/7.5 MB 13.3 MB/s eta 0:00:01
   -----

Algunas de las formas en las que podemos generar matrices en numpy son:
1. Utilizando ceros en todos los elementos (np.zeros)
2. Utilizando unos en todos los elementos (np.ones)
3. Escribiendo los valores de manera explícita (np.array)

En los primeros dos casos, se debe introducir las dimensiones de la matriz entre paréntesis. En el caso de 2 dimensiones, la primer dimensión hace alusión a la cantidad de renglones, y la segunda dimensión especifica la cantidad de columnas.

In [3]:
print("Utilizando ceros")
print(np.zeros((3, 2)))
print("Utilizando unos")
print(np.ones((2, 3)))
print("Escribiendo valores explicitamente")
print(np.array([[1, 2], [3, 4]]))

Utilizando ceros
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Utilizando unos
[[1. 1. 1.]
 [1. 1. 1.]]
Escribiendo valores explicitamente
[[1 2]
 [3 4]]


Al momento de programar con numpy una de los aspectos más importantes al tratar con una matriz son sus dimensiones, para visualizar las dimensiones podemos usar el comando `shape`

In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(f"La matriz tiene {matriz.shape[0]} renglones y {matriz.shape[1]} columnas")
print(matriz.shape)


[[1 2 3]
 [4 5 6]]
La matriz tiene 2 renglones y 3 columnas
(2, 3)


En python utilizamos Numpy porque esta librería permite realizar operaciones matemáticas entre matrices de manera sencilla y rápida

In [5]:
x = np.zeros((2, 2)) # instanciar una matriz de 2x2 inicializada en ceros
print("Inicial:")
print(x)

for i in range(3):
  x += np.ones((2, 2))  # np.ones((2, 2)) crea una matriz de 2x2 inicializada en unos
  print(f"Ciclo {i}:")
  print(x)


Inicial:
[[0. 0.]
 [0. 0.]]
Ciclo 0:
[[1. 1.]
 [1. 1.]]
Ciclo 1:
[[2. 2.]
 [2. 2.]]
Ciclo 2:
[[3. 3.]
 [3. 3.]]


## Broadcasting
En el código anterior sumamos una matriz de 2x2 a otra matriz con las mismas dimensiones (2x2). Matemáticamente la suma se realiza de manera directa, es decir, el elemento de la posición [0, 0] de la primer matriz se suma al elemento de la posición [0, 0] de la segunda matriz.

En numpy, también podriamos sumar una matriz de 2x2 a una de 1x2. Matemáticamente *esto es imposible* sin embargo numpy utiliza el concepto de [`broadcasting`](https://numpy.org/doc/stable/user/basics.broadcasting.html) para realizar este tipo de operaciones.

In [10]:
x = np.zeros((2, 2)) # instanciar una matriz de 2x2 inicializada en ceros
print("Inicial:")
print(x)

for i in range(3):
  x += np.ones((1, 2))  # np.ones((1, 2)) crea una matriz de 1x2 inicializada en unos
  print(f"Ciclo {i}:")
  print(x)

Inicial:
[[0. 0.]
 [0. 0.]]
Ciclo 0:
[[1. 1.]
 [1. 1.]]
Ciclo 1:
[[2. 2.]
 [2. 2.]]
Ciclo 2:
[[3. 3.]
 [3. 3.]]



Cuando numpy hace operaciones en dos matrices, compara sus dimensiones uno a uno. Comienza con las de la derecha y evalua hacia las de la izquierda. Dos dimensiones son compatibles si:
1.   Son iguales
2.   Una dimensión es 1

En esencia, cuando la dimensión es 1 se "repite" o se "estira" para igualar con la cual se quiere realizar la operación.

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([2, 0])

print("La primer matriz es:")
print(a)

print("La segunda matriz es:")
print(b)

print("Al realizar la suma de a con b, b se convierte en:")
b_alterna = np.array([[2, 0], [2, 0], [2, 0]])
print(b_alterna)

print("El resultado de sumar ambas matrices es:")
c = a + b
print(c)

La primer matriz es:
[[1 2]
 [3 4]
 [5 6]]
La segunda matriz es:
[2 0]
Al realizar la suma de a con b, b se convierte en:
[[2 0]
 [2 0]
 [2 0]]
El resultado de sumar ambas matrices es:
[[3 2]
 [5 4]
 [7 6]]


 Podemos hacer lo mismo para matrices con más dimensiones. En el siguiente ejemplo, queremos sumar la matriz A a la matriz B. Estas tienen distintas dimensiones(8x1x6x1 y 7x1x5), numpy entonces iguala las dimensiones de 1 a las que no lo son y el resultado es de dimensionalidad (8x7x6x5)

```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```

Considera el siguiente codigo: Puedes predecir la dimensionalidad de la matriz C antes de correr la celda?

In [13]:
A = np.ones((8,1,6,1))
B = np.ones((5,1,5)) * 2 # Inicializada en 2

C = A + B
print(C.shape)

(8, 5, 6, 5)


# 2. Operaciones matemáticas con numpy

Vamos a realizar diferentes operaciones comunes de algebra lineal en numpy. Considera las siguientes operaciones:



\begin{equation}
  A=Wx\\
\end{equation}

\begin{equation}
  W=
  \begin{bmatrix}
  2 & 3\\
  4 & 5 
  \end{bmatrix}\\
  x = 
  \begin{bmatrix}
  5\\
  6 
  \end{bmatrix}
\end{equation}

Calcula analiticamente el resultado de la operación $A$:
\begin{equation}
  A=  
  \begin{bmatrix}
  ?? \\
  ??
  \end{bmatrix}
\end{equation}

Realicemos ahora la misma operación en numpy:
Puedes usar diferentes operadores para realizar operaciones con matrices
* `np.dot(a,b)` [docs](https://numpy.org/doc/stable/reference/generated/numpy.dot.html): Se utiliza para obtener el producto punto de dos vectores. Sin embargo cuando a o b son matrices, realiza una multiplicacion de matrices.
* `A @ B` [docs](https://numpy.org/doc/stable/reference/generated/numpy.dot.html): Si `A` y `B` son arreglos de numpy (`np.Array([algo])`), realiza una operacion de matrices regular. Recuerda que deben tener la dimensionalidad correcta para la operación.
* `np.multiply(a,b)`: Resulta en el producto hadamart.
* `A * B`: También corresponde a un producto hadamart, es decir una multiplicacion punto a punto. Lo mismo ocurre con los operadores `+`, `-`, y `/`. 

Recuerda que numpy permite realizar operaciones aun cuando las dimensiones no son identicas debido a que realiza un "broadcasting".

### Instrucciones:
Completa el siguiente codigo y compara el resultado de numpy con el analítico.

In [16]:
W = np.array([[2,3],
              [4,5]])
print(W.shape)
# TODO: inicializa x
x = np.array([[5],[6]])
print(x.shape)
# TODO: Realiza la multiplicación de Wx
A = W * x
print(A.shape)
print("Resultado:")
print(A)

(2, 2)
(2, 1)
(2, 2)
Resultado:
[[10 15]
 [24 30]]


Numpy puede hacer muchas cosas interesantes. Por ejemplo podemos calcular los valores y vectores propios de una matriz. Tambien podemos encontrar informacion importante como la magnitud de un vector y determinar si una matriz es positiva definitiva o no. Esto se accede a través de la utilidad de `linalg`. 

Intenta determinar los valores que imprimirá el siguiente código antes de correr la celda.

In [17]:
M = np.array([[3,1],
               [0,2]])

# Calcular la transpuesta
M_transpose = M.T
print("M transpuesta:\n", M_transpose)

# Calcular valores y vectores propios
eig_val, eig_vec = np.linalg.eig(M)
print("M eig_val:", eig_val)
print("M eig_vec:\n", eig_vec) # eig_vec es el vector proio unitario. Cada columna representa un eigenvector


# Calcular la magnitud de el primer vector columna:
norm = np.linalg.norm(M[:,0])
print("Magnitud del primer vector columna de M:\n", norm)

# Determinar si la matriz es positiva definitiva
is_pos_def = np.all(np.linalg.eigvals(M) > 0)
print("Positiva definitiva?", is_pos_def)

# Determinar la inversa
M_inv = np.linalg.inv(M)
print("Inversa de M", M_inv)

# Calcular el determinante
M_det = np.linalg.det(M)
print("Determinante de M:", M_det)

M transpuesta:
 [[3 0]
 [1 2]]
M eig_val: [3. 2.]
M eig_vec:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Magnitud del primer vector columna de M:
 3.0
Positiva definitiva? True
Inversa de M [[ 0.33333333 -0.16666667]
 [ 0.          0.5       ]]
Determinante de M: 6.0


Ahora estas listo para realizar diferentes ejercicios de algebra lineal!

# 3. Ejercicios de álgebra lineal

Resuelve los siguientes ejercicios usando **las funciones de numpy y python adecuadas** e imprime los resultados. Compara la respuesta con el resultado manual calculado en clase.





1. Dada una matriz $X$ imprime los siguientes valores:
\begin{equation}
  X=
  \begin{bmatrix}
  5 & 3 & 5 \\
  8 & 6 & 7 \\
  4 & 2 & 1
  \end{bmatrix}\\
\end{equation}

*   $X_{0,0}$
*   $X_{1,2}$
*   $X_{2,:}$
*   $X_{:,1}$

In [24]:
X = np.array([[5,3,5],
              [8,5,7],
              [4,2,1]])

print(X[0,0])
# TODO, indexa e imprime los valores restantes


5


In [25]:
X = np.array([[5,3,5],
              [8,5,7],
              [4,2,1]])

print(X[0,0])
# TODO, indexa e imprime los valores restantes

print(X[1,2])
print(X[2,:])
print(X[:,1])

5
7
[4 2 1]
[3 5 2]


2. Calcula $Z = G \circ H$

\begin{equation}
  G=
  \begin{bmatrix}
  3 & 5 & 7 \\
  4 & 9 & 8 
  \end{bmatrix}\\
  H = 
  \begin{bmatrix}
  1 & 6 & 3 \\
  0 & 2 & 9 
  \end{bmatrix}\\
\end{equation}

In [26]:
G = np.array([[3,5,7],
              [4,9,8]])
H = np.array([[1,6,3],
              [0,2,9]])

# TODO: Imprime el producto hadamard
print(G * H)

[[ 3 30 21]
 [ 0 18 72]]


3. Calcula $u \cdot v$ para:
\begin{equation}
  u=
  \begin{bmatrix}
  3 \\
  1 
  \end{bmatrix}\\
  v = 
  \begin{bmatrix}
  2 \\
  4
  \end{bmatrix}\\
\end{equation}

In [27]:
# TODO: define los vectores u,v y calcula el producto punto
import numpy as np

# Definir los vectores u y v
u = np.array([3, 1])
v = np.array([2, 4])

# Calcular el producto punto entre u y v
producto_punto = np.dot(u, v)

print("El producto punto entre u y v es:", producto_punto)


El producto punto entre u y v es: 10


4. Dadas las matrices $G, H$ realiza la multiplicación de matrices  $Z=GH$ e imprime la matriz resultante

\begin{equation}
  G=
  \begin{bmatrix}
  1 & 2 \\ 
  3 & 4 \\
  5 & 6 \\ 
  \end{bmatrix}\\
  H = 
  \begin{bmatrix}
  7 & 8 \\
  9 & 10
  \end{bmatrix}
\end{equation}

In [30]:
# TODO: Define las matrices G, H e imprime el resultado de su multiplicación
import numpy as np

# Definir las matrices G y H
G = np.array([[1, 2],
              [3, 4],
              [5, 6]])

H = np.array([[7, 8],
              [9, 10]])

# Realizar la multiplicación de matrices
Z = np.dot(G, H)

# Imprimir la matriz resultante Z
print("El resultado de la multiplicación de matrices GH es:")
print(Z)


El resultado de la multiplicación de matrices GH es:
[[ 25  28]
 [ 57  64]
 [ 89 100]]


5. Imprime la transpuesta de $X$
\begin{equation}
  X=
  \begin{bmatrix}
  1 & 2 & 3\\ 
  4 & 5 & 6 \\
  7 & 8 & 9\\ 
  \end{bmatrix}
\end{equation}

In [34]:
import numpy as np
X = np.arange(1, 10)
X = X.reshape((3,3))
print("Matriz X:")
print(X)
# TODO: imprime la transpuesta de X

# Calcular la transpuesta de X
X_transpuesta = X.T

print("\nLa transpuesta de X es:")
print(X_transpuesta)


Matriz X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

La transpuesta de X es:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


6. Imprime $Z=X^TX$ dada una matriz no simétrica $X$
\begin{equation}
  X=
  \begin{bmatrix}
  1 & 2 & 3\\ 
  4 & 5 & 6 \\
  7 & 8 & 9\\ 
  \end{bmatrix}
\end{equation}

**TODO: Responde las preguntas**
* ¿Que pasa con la matriz Z? ¿es simétrica? Si, es simétrica semi-definida positiva.
* ¿De las propiedades vistas en clase, cual se cumple en este caso? La propiedad que se cumple en este caso es la propiedad de la matriz resultante de un producto de matrices $A = X^TX$.

In [35]:
import numpy as np

X = np.arange(1, 10)
X = X.reshape((3,3))
print("Matriz X:")
print(X)

# Calcular Z = X^T * X
Z = np.dot(X.T, X)

print("\nLa matriz Z es:")
print(Z)


Matriz X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

La matriz Z es:
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


7. Una vez calculada $Z=X^TX$ imprime su transpuesta $Z^T$

**TODO: Responde las preguntas**
* Compara $Z$ y $Z^T$¿Como es la transpuesta de Z? En este caso es igual a Z.
* ¿En base a las propiedades vistas en clase, a cual se debe esto? Esto se basa en la propiedad de simetría que se cumple cuando multiplicamos una matriz por su traspuesta.

In [36]:
# TODO imprime la transpuesta de Z
print(Z.T)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


8. Calcula e imprime los valores y vectores propios de las siguientes matrices
\begin{equation}
  x_1 = 
  \begin{bmatrix}
  1 & 1 \\
  4 & 1
  \end{bmatrix}
  x_2 = 
  \begin{bmatrix}
  2 & 0 \\
  0 & 3
  \end{bmatrix}
\end{equation}

In [40]:
import numpy as np

x_1 = np.array([[1, 1],
                [4, 1]])
# TODO: imprime los valores y vectores propios de x_1

print("Para x_1:")
# Calcular valores y vectores propios de x_1
valores_propios_x1, vectores_propios_x1 = np.linalg.eig(x_1)
print("Valores propios de x_1:")
print(valores_propios_x1)
print("Vectores propios de x_1:")
print(vectores_propios_x1)

print("\nPara x_2:")
x_2 = np.array([[2, 0],
                [0, 3]])
# Calcular valores y vectores propios de x_2
valores_propios_x2, vectores_propios_x2 = np.linalg.eig(x_2)
print("Valores propios de x_2:")
print(valores_propios_x2)
print("Vectores propios de x_2:")
print(vectores_propios_x2)


Para x_1:
Valores propios de x_1:
[ 3. -1.]
Vectores propios de x_1:
[[ 0.4472136  -0.4472136 ]
 [ 0.89442719  0.89442719]]

Para x_2:
Valores propios de x_2:
[2. 3.]
Vectores propios de x_2:
[[1. 0.]
 [0. 1.]]
