In [17]:
import numpy as np

In [18]:
x = np.zeros((2, 2)) # instanciar una matriz de 2x2 inicializada en ceros
print("Inicial:")
print(x)

for i in range(3):
  x += np.ones((1, 2))  # np.ones((1, 2)) crea una matriz de 1x2 inicializada en unos
  print(f"Ciclo {i}:")
  print(x)

Inicial:
[[0. 0.]
 [0. 0.]]
Ciclo 0:
[[1. 1.]
 [1. 1.]]
Ciclo 1:
[[2. 2.]
 [2. 2.]]
Ciclo 2:
[[3. 3.]
 [3. 3.]]


In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([2, 0])

print("La primer matriz es:")
print(a)

print("La segunda matriz es:")
print(b)

print("Al realizar la suma de a con b, b se convierte en:")
b_alterna = np.array([[2, 0], [2, 0], [2, 0]])
print(b_alterna)

print("El resultado de sumar ambas matrices es:")
c = a + b
print(c)

La primer matriz es:
[[1 2]
 [3 4]
 [5 6]]
La segunda matriz es:
[2 0]
Al realizar la suma de a con b, b se convierte en:
[[2 0]
 [2 0]
 [2 0]]
El resultado de sumar ambas matrices es:
[[3 2]
 [5 4]
 [7 6]]


Operaciones matematicas con numpy ejercicio 1

In [21]:
W = np.array([[2,3],
              [4,5]])
print(W.shape)
# TODO: inicializa x
x = np.array([[5,
              6]])
print(x.shape)
# TODO: Realiza la multiplicación de Wx
x_transp=np.transpose(x)
A = np.dot(W,x_transp)
print(A.shape)
print("Resultado:")
print(A)

(2, 2)
(1, 2)
(2, 1)
Resultado:
[[28]
 [50]]


Ejercicio 2 numpy:
Primero la transpuesta de M es:
 
\begin{equation}
Mtransp=
\begin{bmatrix}
3 & 0\\
1 & 2
\end{bmatrix}

\end{equation}

Los eigenval de M: [2,3] y los eigen vectors:

\begin{equation}
\begin{bmatrix}
1 & -0.707106\\
0 & 0.707106
\end{bmatrix}

\end{equation}

Magnitud del primer vector M: 3

is_pos_def: **False** porque M no es una matriz definida positiva (Al correr vi que me equvioqué pero fui honesto)

Inversa de M:

\begin{equation}
Mtransp=
\begin{bmatrix}
0.66667 & -0.33333\\
0 & 0.5
\end{bmatrix}

\end{equation}

Determinante de M: 6 porque 3x2-1x0=6

In [22]:
M = np.array([[3,1],
               [0,2]])

# Calcular la transpuesta
M_transpose = M.T
print("M transpuesta:\n", M_transpose)

# Calcular valores y vectores propios
eig_val, eig_vec = np.linalg.eig(M)
print("M eig_val:", eig_val)
print("M eig_vec:\n", eig_vec) # eig_vec es el vector proio unitario. Cada columna representa un eigenvector


# Calcular la magnitud de el primer vector columna:
norm = np.linalg.norm(M[:,0])
print("Magnitud del primer vector columna de M:\n", norm)

# Determinar si la matriz es positiva definitiva
is_pos_def = np.all(np.linalg.eigvals(M) > 0)
print("Positiva definitiva?", is_pos_def)

# Determinar la inversa
M_inv = np.linalg.inv(M)
print("Inversa de M", M_inv)

# Calcular el determinante
M_det = np.linalg.det(M)
print("Determinante de M:", M_det)

M transpuesta:
 [[3 0]
 [1 2]]
M eig_val: [3. 2.]
M eig_vec:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Magnitud del primer vector columna de M:
 3.0
Positiva definitiva? True
Inversa de M [[ 0.33333333 -0.16666667]
 [ 0.          0.5       ]]
Determinante de M: 6.0


Ejercicios de algebra lineal

In [24]:
X= np.array([[5,3,5],
             [8,6,7],
             [4,2,1]])
print(X[0,0])
print(X[1,2])
print(X[2,:])
print(X[:,1])

5
7
[4 2 1]
[3 6 2]
