In [2]:
import numpy as np

In [18]:
import numpy as np
x = np.zeros((2, 2)) # instanciar una matriz de 2x2 inicializada en ceros
print("Inicial:")
print(x)

for i in range(3):
  x += np.ones((1, 2))  # np.ones((1, 2)) crea una matriz de 1x2 inicializada en unos
  print(f"Ciclo {i}:")
  print(x)

Inicial:
[[0. 0.]
 [0. 0.]]
Ciclo 0:
[[1. 1.]
 [1. 1.]]
Ciclo 1:
[[2. 2.]
 [2. 2.]]
Ciclo 2:
[[3. 3.]
 [3. 3.]]


In [19]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([2, 0])

print("La primer matriz es:")
print(a)

print("La segunda matriz es:")
print(b)

print("Al realizar la suma de a con b, b se convierte en:")
b_alterna = np.array([[2, 0], [2, 0], [2, 0]])
print(b_alterna)

print("El resultado de sumar ambas matrices es:")
c = a + b
print(c)

La primer matriz es:
[[1 2]
 [3 4]
 [5 6]]
La segunda matriz es:
[2 0]
Al realizar la suma de a con b, b se convierte en:
[[2 0]
 [2 0]
 [2 0]]
El resultado de sumar ambas matrices es:
[[3 2]
 [5 4]
 [7 6]]


Operaciones matematicas con numpy ejercicio 1

In [21]:
import numpy as np
W = np.array([[2,3],
              [4,5]])
print(W.shape)
# TODO: inicializa x
x = np.array([[5,
              6]])
print(x.shape)
# TODO: Realiza la multiplicación de Wx
x_transp=np.transpose(x)
A = np.dot(W,x_transp)
print(A.shape)
print("Resultado:")
print(A)

(2, 2)
(1, 2)
(2, 1)
Resultado:
[[28]
 [50]]


Ejercicio 2 numpy:
Primero la transpuesta de M es:
 
\begin{equation}
Mtransp=
\begin{bmatrix}
3 & 0\\
1 & 2
\end{bmatrix}

\end{equation}

Los eigenval de M: [2,3] y los eigen vectors:

\begin{equation}
\begin{bmatrix}
1 & -0.707106\\
0 & 0.707106
\end{bmatrix}

\end{equation}

Magnitud del primer vector M: 3

is_pos_def: **False** porque M no es una matriz definida positiva (Al correr vi que me equvioqué pero fui honesto)

Inversa de M:

\begin{equation}
Mtransp=
\begin{bmatrix}
0.66667 & -0.33333\\
0 & 0.5
\end{bmatrix}

\end{equation}

Determinante de M: 6 porque 3x2-1x0=6

In [22]:
import numpy as np
M = np.array([[3,1],
               [0,2]])

# Calcular la transpuesta
M_transpose = M.T
print("M transpuesta:\n", M_transpose)

# Calcular valores y vectores propios
eig_val, eig_vec = np.linalg.eig(M)
print("M eig_val:", eig_val)
print("M eig_vec:\n", eig_vec) # eig_vec es el vector proio unitario. Cada columna representa un eigenvector


# Calcular la magnitud de el primer vector columna:
norm = np.linalg.norm(M[:,0])
print("Magnitud del primer vector columna de M:\n", norm)

# Determinar si la matriz es positiva definitiva
is_pos_def = np.all(np.linalg.eigvals(M) > 0)
print("Positiva definitiva?", is_pos_def)

# Determinar la inversa
M_inv = np.linalg.inv(M)
print("Inversa de M", M_inv)

# Calcular el determinante
M_det = np.linalg.det(M)
print("Determinante de M:", M_det)

M transpuesta:
 [[3 0]
 [1 2]]
M eig_val: [3. 2.]
M eig_vec:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Magnitud del primer vector columna de M:
 3.0
Positiva definitiva? True
Inversa de M [[ 0.33333333 -0.16666667]
 [ 0.          0.5       ]]
Determinante de M: 6.0


Ejercicios de algebra lineal

In [1]:
import numpy as np
X= np.array([[5,3,5],
             [8,6,7],
             [4,2,1]])
print(X[0,0])
print(X[1,2])
print(X[2,:])
print(X[:,1])

NameError: name 'np' is not defined

Algebra lineal pt2

In [6]:
import numpy as np
G = np.array([[3,5,7],
              [4,9,8]])
H = np.array([[1,6,3],
              [0,2,9]])

Hadamard=G*H
print(Hadamard)

[[ 3 30 21]
 [ 0 18 72]]


Algebra lineal pt.3

In [5]:
import numpy as np
u = np.array([[3],
              [1]])
v = np.array([[2],
              [4]])

producto_punto= np.dot(u.flatten(), v.flatten())
print(producto_punto)

10


Algebra lineal pt.4

In [8]:
import numpy as np
G = np.array([[1,2],
              [3,4],
              [5,6]])

H = np.array([[7,8],
              [9,10]])

multiplicaciongh=np.dot(G,H)
print("Multiplicacion resultado:")
print(multiplicaciongh)

Multiplicacion resultado:
[[ 25  28]
 [ 57  64]
 [ 89 100]]


Algebbra lineal pt.5

In [10]:
import numpy as np
X = np.arange(1,10)
X = X.reshape((3,3))
print(X)
print("")
Xtransp=X.T
print(Xtransp)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Algebra lineal pt.6

In [11]:
import numpy as np
X = np.arange(1,10)
X = X.reshape((3,3))
print(X)
print("")

Z=np.dot(X.T,X)
print (Z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


¿Que pasa con la matriz Z? ¿es simétrica?**Si es simetrica porque es igual a su traspuesta.**


¿De las propiedades vistas en clase, cual se cumple en este caso? **Que el producto siempre es simetrico**

ALgebra lineal pt.7

In [14]:
import numpy as np
X = np.arange(1,10)
X = X.reshape((3,3))

Z=np.dot(X.T,X)
print (Z)
print("")
Ztrasp=Z.T
print(Ztrasp)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


Compara Zy Z^T ,como es la transpuesta de z?
**Quedan igual**

En base a las propiedades vistas, a cual se debe esto?
**A la del producto exterior de un vector por si mismo, cuando se realiza producto punto de cada vector fila con cada vector fila y queda en matriz simetrica**

Algebra lineal pt8

In [15]:
import numpy as np
x_1 = np.array([[1,1],
                [4,1]])
print("Matriz x1:")
print(x_1)

valorespropios_x1, vectorespropios_x1 = np.linalg.eig(x_1)

print("Valores propios x1:")
print(valorespropios_x1)
print("")

print("Vectores propios x1:")
print(vectorespropios_x1)
x_2 = np.array([[2,0],
                [0,3]])

print("Matriz x2:")
print(x_2)

valorespropios_x2, vectorespropios_x2 = np.linalg.eig(x_2)

print("Valores propios x2:")
print(valorespropios_x2)
print("")

print("Vectores propios x2:")
print(vectorespropios_x2)

Matriz x1:
[[1 1]
 [4 1]]
Valores propios x1:
[ 3. -1.]

Vectores propios x1:
[[ 0.4472136  -0.4472136 ]
 [ 0.89442719  0.89442719]]
Matriz x2:
[[2 0]
 [0 3]]
Valores propios x2:
[2. 3.]

Vectores propios x2:
[[1. 0.]
 [0. 1.]]
